stages:
  preprocess:
    cmd: python src/YOLO/preprocess.py
    deps:
      - src/preprocess.py
      - params.yaml
      - datasets/raw/train/images
      - datasets/raw/train/labels
    params:
      - preprocess.input_images
      - preprocess.input_labels
      - preprocess.output_images
      - preprocess.output_labels
    outs:
      - datasets/processed/train/images
      - datasets/processed/train/labels
  train_initial:
    cmd: python src/YOLO/train.py --mode initial
      deps:
        - src/train.py
        - params.yaml
        - data.yaml
        - datasets/processed/train/images
        - datasets/processed/train/labels
      params:
        - train.model_path
      outs:
        - models/initial_model.pt
  fine-tune:
    cmd: python src/YOLO/train.py --mode fine-tune
    deps:
      - src/train.py
      - params.yaml
      - data.yaml
      - models/train.pt
      - datasets/processed/train/images
      - datasets/processed/train/labels
    params:
      - train.model_path
    outs:
      - models/fine-tune-(v8m).pt
  evaluate:
    cmd: python src/YOLO/evaluate.py --model_path models/optimized_model.pt --data_path datasets/processed/data.yaml
    deps:
      - src/evaluate.py
      - params.yaml
      - data.yaml
      - models/fine-tune-(v8m).pt
      - datasets/processed/test/images
      - datasets/processed/test/labels
    outs:
      - reports/evaluation.txt
  train_optimized:
    cmd: python src/YOLO/train.py --mode optimized -- config results/best_params.yaml
    deps:
      - src/train.py
      - params.yaml
      - results/best_params.yaml
      - datasets/processed/train/images
      - datasets/processed/train/labels
    params:
      - train
    outs:
      - models/optimized_model.pt
  optimize:
    cmd: python src/YOLO/optimize.py
    deps:
      - src/optimize.py
      - params.yaml
      - datasets/processed/train/images
      - datasets/processed/train/labels
    params:
      - train
    outs: 
      - results/best_params.yaml