stages:
  # Preprocessing for YOLO training data
  preprocess_YOLO_train:
    cmd: python src/preprocess.py --model YOLO --dataset train
    deps:
      - src/preprocess.py
      - params.yaml
      - datasets/YOLO/raw/train/images
      - datasets/YOLO/raw/train/labels
    params:
      - YOLO.preprocess.train
    outs:
      - datasets/YOLO/processed/train/images
      - datasets/YOLO/processed/train/labels

  # Preprocessing for SSD training data (with augmentations)
  preprocess_SSD_train:
    cmd: python src/preprocess.py --model SSD --dataset train
    deps:
      - src/preprocess.py
      - params.yaml
      - datasets/SSD/raw/train/images
      - datasets/SSD/raw/train/labels
    params:
      - SSD.preprocess.train
    outs:
      - datasets/SSD/processed/train.tfrecord

  # Preprocessing for SSD validation data (no augmentations)
  preprocess_SSD_valid:
    cmd: python src/preprocess.py --model SSD --dataset valid
    deps:
      - src/preprocess.py
      - params.yaml
      - datasets/SSD/raw/valid/images
      - datasets/SSD/raw/valid/labels
    params:
      - SSD.preprocess.valid
    outs:
      - datasets/SSD/raw/val.tfrecord

  # Initial training for YOLO
  train_initial_YOLO:
    cmd: python src/YOLO/train.py --mode initial
    deps:
      - src/YOLO/train.py
      - params.yaml
      - YOLO/data.yaml
      - datasets/YOLO/processed/train/images
      - datasets/YOLO/processed/train/labels
    params:
      - YOLO.train
    outs:
      - models/YOLO/initial_model.pt

  # Fine-tuning for YOLO
  fine-tune_YOLO:
    cmd: python src/YOLO/train.py --mode fine-tune
    deps:
      - src/YOLO/train.py
      - params.yaml
      - YOLO/data.yaml
      - models/YOLO/initial_model.pt
      - datasets/YOLO/processed/train/images
      - datasets/YOLO/processed/train/labels
    params:
      - YOLO.train
    outs:
      - models/YOLO/fine-tune-(v8m).pt

  # Evaluation for YOLO
  evaluate_YOLO:
    cmd: python src/YOLO/evaluate.py --model_path models/YOLO/optimized_model.pt --data_path YOLO/data.yaml
    deps:
      - src/YOLO/evaluate.py
      - params.yaml
      - YOLO/data.yaml
      - models/YOLO/optimized_model.pt
    outs:
      - reports/YOLO/evaluation.txt

  # Optimization for YOLO
  optimize_YOLO:
    cmd: python src/YOLO/optimize.py
    deps:
      - src/YOLO/optimize.py
      - params.yaml
      - YOLO/data.yaml
      - datasets/YOLO/processed/train/images
      - datasets/YOLO/processed/train/labels
    params:
      - YOLO.train
    outs:
      - results/YOLO/best_params.yaml

  # Optimized training for YOLO
  train_optimized_YOLO:
    cmd: python src/YOLO/train.py --mode optimized --config results/YOLO/best_params.yaml
    deps:
      - src/YOLO/train.py
      - params.yaml
      - YOLO/data.yaml
      - results/YOLO/best_params.yaml
      - datasets/YOLO/processed/train/images
      - datasets/YOLO/processed/train/labels
    params:
      - YOLO.train
    outs:
      - models/YOLO/optimized_model.pt