YOLO:
  # preprocess:
  #   train:
  #     input_images: 'datasets/YOLO/raw/train/images'
  #     input_labels: 'datasets/YOLO/raw/train/labels'
  #     output_images: 'datasets/YOLO/processed/train/images'
  #     output_labels: 'datasets/YOLO/processed/train/labels'
  train:

    data: 'data.yaml'
    fine_tuned_model: 'models/YOLO/yolo_fine_tuned.pt'
  base_model: "models/YOLO/fine_tuned_yolo_model.pt" 
  optimized_model: "models/YOLO/best_yolo_optimized.pt"  
  initial_model: "models/YOLO/initial_model.pt"


SSD:
  train:
    data: 'src/yolo/data.yaml'
    model: 'ssdlite320_mobilenet_v3_large'
    num_classes: 6  # 5 classes + background (0 reserved for background)
    width_mult: 1.0
    epochs: 50
    batch: 16
    lr: 0.001
  base_model: 'models/ssd/best_ssd_model.pth'
  optimized_model: "models/ssd/best_optimized_ssd_model.pth"  # Optimized SSD model from training

# Class names from data.yaml (shared across YOLO and SSD)
class_names: ['bus', 'car', 'motorcycle', 'person', 'truck']