YOLO:
  preprocess:
    train:
      input_images: 'datasets/YOLO/raw/train/images'
      input_labels: 'datasets/YOLO/raw/train/labels'
      output_images: 'datasets/YOLO/processed/train/images'
      output_labels: 'datasets/YOLO/processed/train/labels'
  train:
    data: 'src/yolo/data.yaml'
    model: 'models/YOLO/fine-tune-(v8m).pt'

SSD:
  train:
    data: 'src/yolo/data.yaml'
    model: 'ssdlite320_mobilenet_v3_large'
    model_path: 'models/ssd/best_ssd_model.pth'
    num_classes: 6  # 5 classes + background
    epochs: 50
    batch: 16
    lr: 0.001