preprocess:
  input_images: 'datasets/raw/train/images'
  input_labels: 'datasets/raw/train/labels'
  output_images: 'datasets/processed/train/images'
  output_labels: 'datasets/processed/train/labels'
  
train: 
  data: 'data.yaml'
  model: models/coco-trained-v1.pt

