preprocess:
  input: 'datasets/train/images'
  output: 'datasets/train/processed_images'
train: 
  data: 'datasets/train/processed_images'
  model: models/yolov8n.pt
  # other hyperparameters go here for training
val: 
  data: 'datasets/valid/images'
test: 
  data: 'datasets/test/images'

nc: 2
names: ['2-Wheeler VRU', 'Pedestrian VRU']