preprocess:
  input_images: 'datasets/raw/train/images'
  input_labels: 'datasets/raw/train/labels'
  val_input_images: 'datasets/raw/val/images'
  val_input_labels: 'datasets/raw/val/labels'
  tfrecord_output: 'data/tfrecords/train.tfrecord'
  val_tfrecord_output: 'data/tfrecords/val.tfrecord'

train:
  ssd_config: 'configs/SSD/ssd_pipeline.config'
  ssd_model_dir: 'models/SSD/initial_model'
  num_steps: 50000